### ISSUE TITLE
Calculation of SquareMatrixElement

### ISSUE THREAD

**Issue by dkahrama** [magv/alibrary#5]
Code:
SqrAmpLoop2 = amplitudes0*AmpConjugate[amplitudes2];

the problem is that amplitudes0 is generated from the LO vertex which is only one diagram and amplitudes2 is generated from the NNLO vertex diagrams which are 29 diagrams. How can I calculate the SquareMatrix since the dimensions do not match?

I am still a beginner. I hope u can help. Thanks.

**Comment by magv** [comment]
If you would be calculating this on paper, what would have happened? That is the first question every time -- what goes into code directly follows from that.

In your case full amplitude is the sum of the amplitudes of diagrams, and your square amplitude is the product of the LO amplitude times the complex conjugated NNLO amplitude. You're missing the sum, it seems. See how I do it e.g. [here](/magv/alibrary/blob/c09d909dd99c8037dd85e315f07d318269899b3f/atestsuite.m#L319)

PS. I would advise to complex-conjugate the LO amplitude, not the NNLO; if you're conjugating a loop amplitude (as opposed to a tree-level), you need to remember that you have conjugated the `+i0` propagator prescription (making it `-i0`), which will mean you'll need to conjugate the the values of the integrals you will be inserting later.

**Comment by dkahrama** [comment]
I tried it now in two different ways. Maybe u can look at the the  
outputs and u can help me further. I appreciate every help and  
response. thank u.






Quoting Vitaly Magerya ***@***.***>:
