### ISSUE TITLE
2 loop A->qQ

### ISSUE THREAD

**Issue by dkahrama** [magv/alibrary#7]
I tried to calculate the 2 loop corrections for the relevant diagrams.It worked for the one loop. For the 2 loop one proportional to Nf did it work as well. But somehow some diagrams like the one with a gluon self energy insertion or the simple ladder diagram it does not work. I will attach a file for the ladder diagram for u to see and i would appreciate any help. I would expect the resulting master integral to be a bubble Integral squared after the IBP reduction but i get something different. Thank u very much. 
[gamma_qQ2_Dia7.pdf](https://github.com/magv/alibrary/files/12886351/gamma_qQ2_Dia7.pdf)

**Comment by magv** [comment]
Hi. Is the problem that the master integrals are not what you expect? In general if you don't specify which basis of master integrals you prefer, the IBP solver will choose *some basis*, but not any particular one -- this is not an error, since you always have the freedom to choose a different basis. If you have a specific basis in mind, you can pass it as a list into the `PreferredMasters` option of [`KiraIBP`](https://magv.github.io/alibrary/alibrary.html#KiraIBP).

For other problems, please:

1. Attach the code you are running so I could run it too, preferably the smallest fragment of code that reproduces the problem.
2. Specify what output you are seeing from this fragment.
3. Specify what output you expect to see instead (and why).

**Comment by dkahrama** [comment]
Hi Vitaly thanks for the response. I am comparing my final results for the form factor with the following paper [https://arxiv.org/pdf/hep-ph/0507039]. And the master integrals are from [https://arxiv.org/pdf/hep-ph/0507061].
I am trying to calculate all diagrams (page 13 above mentioned paper) which contribute to the two loop quark form factor individually. The result for the ladder diagram (diagram L) which I calculated is different from the expected one. Since the same procedure worked for the diagram QL it should work for the diagram L too. I cannot see and really understand where the mistake is. I wrote the expected result at the end. I will attach a file which u can copy and paste into a mathematica notebook to run it too. Many thanks for your help.
[diagram7.txt](https://github.com/magv/alibrary/files/13029754/diagram7.txt)

**Comment by dkahrama** [comment]
This is the right one excuse me.
[gamma_qQ2_Dia7.txt](https://github.com/magv/alibrary/files/13030982/gamma_qQ2_Dia7.txt)

**Comment by magv** [comment]
I'm not quite sure where the error is, but can I ask you to double-check the master value substitution rules? The code sets two of the three master integrals to the same value, which looks suspicious to me.

What I can tell you, is that some time ago my colleagues have used alibrary to perform the exact calculation you are attempting now, and the results matched the literature. So you can be confident that it is possible to make it work :)

**Comment by dkahrama** [comment]
I checked it up again and it seems that one of the master integrals is a bubble topology squared. After Insertion, the result is still not correct :(

**Comment by dkahrama** [comment]
Is there a way to to just take out one diagram individually, map its amplitude and do the reduction to master integrals instead of calculating the squared matrix element with the leading order diagram first and then do the reduction?

**Comment by dkahrama** [comment]
If I try to do it the exact way as done in the example for the photon-propagator, I always get a error by running through FORM:
ERROR: flavorsumwithcharge: leftover light flavors; unexpected flavor structure
This is the file to run:
Thanks for your help and time:)
[gamma_qQ2_Dia7_2.txt](https://github.com/magv/alibrary/files/13063802/gamma_qQ2_Dia7_2.txt)

**Comment by magv** [comment]
The error says there are leftover flavor structure, i.e. open flavor indices -- these need to be connected to form a trace, which is normally done with either multiplying by a complex-conjugated amplitude and summing over the final states (as you have in the previous code example), or with projectors.

In your case you initially calculated tree-amplitude * two-loop-amplitude; why don't you just calculate tree-amplitude * two-loop-amplitude[[diagram 7]] instead? This multiplication by the tree amplitude is what is missing in the latest code example.

**Comment by dkahrama** [comment]
I solved the problem. Everything matches now. If i want to calculate the form factor for H->gg, how do i need to choose the projector in order to calculate the amplitude? Thanks for ur help.

**Comment by magv** [comment]
Glad it worked out for you.

For H->gg you need a projector for the final states, unless you are multiplying by e.g. complex-conjugated tree level amplitude, in which case due to H being a scalar there will be nothing left to project out.
